/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COPIAS;

import Connection.MyConnection;
//import ProyectoHeladeria.LoginImagen1;
//import ProyectoHeladeria.PruebaTabla;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Annibel
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    
    DefaultTableModel Factura;
    
    public Factura() {
        initComponents();
        
        this.Factura = (DefaultTableModel) TablaFactura.getModel();
        
        Mostrardatos("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductos = new javax.swing.JLabel();
        lblCodFactura = new javax.swing.JLabel();
        jtCodigoF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        lblFecha = new javax.swing.JLabel();
        jtFecha = new javax.swing.JTextField();
        jtPago = new javax.swing.JTextField();
        jtValidoh = new javax.swing.JTextField();
        lblValidoh = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        jbFactura = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbVender = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(51, 0, 153));
        lblProductos.setText("FACTURA");

        lblCodFactura.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblCodFactura.setText("Codigo Factura");

        jtCodigoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoFActionPerformed(evt);
            }
        });

        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturaMouseClicked(evt);
            }
        });
        TablaFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaFacturaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFactura);

        lblFecha.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblFecha.setText("Fecha");

        jtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFechaActionPerformed(evt);
            }
        });
        jtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtFechaKeyPressed(evt);
            }
        });

        lblValidoh.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblValidoh.setText("Valido hasta");

        lblPago.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblPago.setText("Pago");

        jbFactura.setText("FACTURA");
        jbFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFacturaActionPerformed(evt);
            }
        });

        jbLimpiar.setText("LIMPIAR");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbVender.setText("VENDER");
        jbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVenderActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblTotal.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbFactura)
                        .addGap(66, 66, 66)
                        .addComponent(jbLimpiar)
                        .addGap(72, 72, 72)
                        .addComponent(jbVender)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFecha)
                                    .addComponent(lblCodFactura))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtCodigoF, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jtFecha)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValidoh)
                                    .addComponent(lblPago))
                                .addGap(62, 62, 62)
                                .addComponent(jtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtValidoh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(lblProductos)
                    .addContainerGap(824, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodFactura)
                            .addComponent(jtCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPago)
                            .addComponent(jtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValidoh)
                            .addComponent(jtValidoh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbFactura)
                            .addComponent(jbLimpiar)
                            .addComponent(jbVender)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(lblProductos)
                    .addContainerGap(352, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCodigoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoFActionPerformed

    private void TablaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturaMouseClicked
        // TODO add your handling code here:

        try {
            String CodigoF = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),0);
            String Fecha = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),1);
            String Pago = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),2);
            String Valido = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),3);
            String Total = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),4);

            jtCodigoF.setText(CodigoF);
            jtFecha.setText(Fecha);
            jtPago.setText(Pago);
            jtValidoh.setText(Valido);
            jtTotal.setText(Total);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaFacturaMouseClicked

    private void jtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFechaActionPerformed

    private void jtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFechaKeyPressed
        // TODO add your handling code here:

        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                String B = jtCodigoF.getText()+"";
                Mostrardatos(B);
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_jtFechaKeyPressed

    private void jbFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFacturaActionPerformed
        // TODO add your handling code here:
        
        Connection cn=MyConnection.getConnection();
        
        try{
            JasperReport jr = (JasperReport) JRLoader.loadObject(Factura.class.getResource("/Reporte/FacturaF.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Reporte Factura");
            

           JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
           JasperViewer jv = new JasperViewer(jp, false);
           jv.setVisible(true); 
        
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_jbFacturaActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:

        Limpiar();
        Mostrardatos("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVenderActionPerformed
        // TODO add your handling code here:
        
        Enviar();
        
//        int Can1, Can2, ProductoV = 0;
//        
//        Can1 = Integer.parseInt(jtCantidad.getText());
//        Can2 = Integer.parseInt(jtCantidad.getText());
//        ProductoV = Can1-Can2;
//        
//        jtCantidad.setText(String.valueOf(ProductoV));
//        
//        String id = jtId.getText();
//        String nom = jtNombre.getText();
//        String pre = jtPrecio.getText();
//        String dis = jtDisponible.getText();
//        String can = jtCantidad.getText();
//        
//        PreparedStatement ps;
//        String query = "UPDATE `Producto` SET `CantidadDisponible`= ? WHERE `ID_producto`=";
//        try {
//            ps = MyConnection.getConnection().prepareStatement(query);
//
//            if(ps.executeUpdate() > 0)
//            {
//                JOptionPane.showMessageDialog(null, "Producto Vendido");
//                Limpiar();
//                Mostrardatos("");
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "error "+ex);
//        }
        
        
    }//GEN-LAST:event_jbVenderActionPerformed

    
    private void Enviar(){
       
//        String id = jtCodigoF.getText();
//        String cantidad = jtCantidad.getText();
//        
//       PreparedStatement ps;
//        String query = "UPDATE `Producto` SET `CantidadDisponible`= CantidadDisponible - "+cantidad+" WHERE `ID_producto`=" + id;
//        try {
//            ps = MyConnection.getConnection().prepareStatement(query);
//
//            if(ps.executeUpdate() > 0)
//            {
//                JOptionPane.showMessageDialog(null, "Producto Vendido");
//                Limpiar();
//                Mostrardatos("");
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "error "+ex);
//        }
    }
    
    private void TablaFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaFacturaKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String B = jtCodigoF.getText()+"";
        Mostrardatos(B);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaFacturaKeyPressed

    
    
    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            Factura.addColumn("Codigo_factura");
            Factura.addColumn("fecha_factu");
            Factura.addColumn("Forma_pago");
            Factura.addColumn("Valido_hasta");
            Factura.addColumn("Total");

            this.TablaFactura.setModel(Factura);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM `Venta`";
            }
            else{
            sql="SELECT * FROM `Venta` WHERE `Codigo_factura`='"+valor+"'";
            } 

            String []datos=new String [6];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);

            Factura.addRow(datos);
            }
            TablaFactura.setModel(Factura);
            }catch(SQLException ex){
            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    
     public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        Factura.setColumnCount(0);
        Factura.setRowCount(0);
        TablaFactura.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    public void Limpiar(){
        //Funcion para limpiar los text field existentes
        try{
        jtCodigoF.setText("");
        jtFecha.setText("");
        jtPago.setText("");
        jtValidoh.setText("");
        jtTotal.setText("");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbFactura;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbVender;
    private javax.swing.JTextField jtCodigoF;
    private javax.swing.JTextField jtFecha;
    private javax.swing.JTextField jtPago;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JTextField jtValidoh;
    private javax.swing.JLabel lblCodFactura;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValidoh;
    // End of variables declaration//GEN-END:variables
}
