package COPIAS;

import Connection.MyConnection;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A19B47948
 */
public class Facturacion extends javax.swing.JFrame {

    
    DefaultTableModel Factura;
    
    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
        
        this.Factura = (DefaultTableModel) TablaFactura.getModel();
        Mostrardatos("");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigoF = new javax.swing.JLabel();
        lblFechaF = new javax.swing.JLabel();
        lblHoraF = new javax.swing.JLabel();
        tfFactura = new javax.swing.JTextField();
        tfFechaF = new javax.swing.JTextField();
        tfHora = new javax.swing.JTextField();
        lblCajera = new javax.swing.JLabel();
        lblFormapago = new javax.swing.JLabel();
        lblDatosF = new javax.swing.JLabel();
        lblNombreC = new javax.swing.JLabel();
        tfCodigoC = new javax.swing.JTextField();
        lblCodigoC = new javax.swing.JLabel();
        tfNombreC = new javax.swing.JTextField();
        tfCajera = new javax.swing.JTextField();
        tfFormaPago = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDatosP = new javax.swing.JLabel();
        lblNombreP = new javax.swing.JLabel();
        lblSaborH = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        jbGuardar = new javax.swing.JButton();
        tfCantidad = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jbImprimirF = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        tfProducto = new javax.swing.JTextField();
        tfSabor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCodigoF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCodigoF.setText("No. Factura");

        lblFechaF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaF.setText("Fecha");

        lblHoraF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraF.setText("Hora");

        tfFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFacturaKeyPressed(evt);
            }
        });

        lblCajera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCajera.setText("Cajera");

        lblFormapago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFormapago.setText("Forma de pago");

        lblDatosF.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblDatosF.setText("Datos Factura/Cliente");

        lblNombreC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreC.setText("Nombre Cliente");
        lblNombreC.setToolTipText("");

        lblCodigoC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCodigoC.setText("Codigo Cliente");
        lblCodigoC.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaF)
                                    .addComponent(tfFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCajera)
                                    .addComponent(tfCajera)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodigoF)
                                .addGap(105, 105, 105)
                                .addComponent(lblHoraF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCodigoC)
                                        .addGap(100, 100, 100))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFormapago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfFormaPago)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblDatosF)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosF)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoF)
                    .addComponent(lblHoraF)
                    .addComponent(lblFormapago)
                    .addComponent(lblCodigoC))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCajera)
                            .addComponent(lblNombreC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCajera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDatosP.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblDatosP.setText("Datos Producto");

        lblNombreP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreP.setText("Producto");

        lblSaborH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaborH.setText("Sabor");

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantidad.setText("Cantidad");

        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturaMouseClicked(evt);
            }
        });
        TablaFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaFacturaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFactura);

        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Total");

        jbImprimirF.setText("IMPRIMIR");
        jbImprimirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirFActionPerformed(evt);
            }
        });

        jbLimpiar.setText("LIMPIAR");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 237, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addGap(18, 18, 18)
                                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(219, 219, 219)
                                .addComponent(jbImprimirF)
                                .addGap(68, 68, 68)
                                .addComponent(jbLimpiar))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblNombreP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCantidad)
                                        .addComponent(lblSaborH))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(tfSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDatosP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDatosP)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreP)
                            .addComponent(tfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaborH)
                            .addComponent(tfSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbImprimirF)
                    .addComponent(jbLimpiar))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturaMouseClicked
        // TODO add your handling code here:
        try {
            String NoFactura = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),0);
            String Fecha = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),1);
            String Hora = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),2);
            String Cajera = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),3);
            String Cliente = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),4);
            String FormaPago = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),5);
            String Producto = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),6);
            String Sabor = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),7);
            String Cantidad = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),8);
            String Total = (String) Factura.getValueAt(TablaFactura.getSelectedRow(),9);

            tfFactura.setText(NoFactura);
            tfFechaF.setText(Fecha);
            tfHora.setText(Hora);
            tfCajera.setText(Cajera);
            tfNombreC.setText(Cliente);
            tfFormaPago.setText(FormaPago);
            tfProducto.setText(Producto);
            tfSabor.setText(Sabor);
            tfCantidad.setText(Cantidad);
            tfTotal.setText(Total);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaFacturaMouseClicked

    private void TablaFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaFacturaKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String B = tfFactura.getText()+"";
        Mostrardatos(B);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaFacturaKeyPressed

    private void jbImprimirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirFActionPerformed
        // TODO add your handling code here:
        Connection cn=MyConnection.getConnection();
        
        try{
            JasperReport jr = (JasperReport) JRLoader.loadObject(Factura.class.getResource("/Reporte/Facturacion.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Reporte Factura");
            

           JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
           JasperViewer jv = new JasperViewer(jp, false);
           jv.setVisible(true); 
        
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jbImprimirFActionPerformed

    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            Factura.addColumn("NoFactura");
            Factura.addColumn("FechaF");
            Factura.addColumn("HoraF");
            Factura.addColumn("Cajera");
            Factura.addColumn("NombreCliente");
            Factura.addColumn("FormaPago");
            Factura.addColumn("Producto");
            Factura.addColumn("Sabor");
            Factura.addColumn("Cantidad");
            Factura.addColumn("Total");

            this.TablaFactura.setModel(Factura);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM `Facturacion`";
            }
            else{
            sql="SELECT * FROM `Facturacion` WHERE `NoFactura`='"+valor+"'";
            } 

            String []datos=new String [10];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);
            datos[7]=rs.getString(8);
            datos[8]=rs.getString(9);
            datos[9]=rs.getString(10);

            Factura.addRow(datos);
            }
            TablaFactura.setModel(Factura);
            }catch(SQLException ex){
            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    
     public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        Factura.setColumnCount(0);
        Factura.setRowCount(0);
        TablaFactura.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    public void Limpiar(){
        //Funcion para limpiar los text field existentes
        try{
        tfFactura.setText("");
        tfFechaF.setText("");
        tfHora.setText("");
        tfCajera.setText("");
        tfNombreC.setText("");
        tfFormaPago.setText("");
        tfProducto.setText("");
        tfSabor.setText("");
        tfCantidad.setText("");
        tfTotal.setText("");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
        Mostrardatos("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        String nofac = tfFactura.getText();
        String fecha = tfFechaF.getText();
        String hora = tfHora.getText();
        String caj = tfCajera.getText();
        String nomcli = tfNombreC.getText();
        String forpag = tfFormaPago.getText();
        String pro = tfProducto.getText();
        String sab = tfSabor.getText();
        String can = tfCantidad.getText();
        String total = tfTotal.getText();
        
        PreparedStatement ps;
        String query = "INSERT INTO `Facturacion`(`NoFactura`,`FechaF`,`HoraF`,`Cajera`,`NombreCliente`,`FormaPago`,`Producto`,`Sabor`,`Cantidad`,`Total`) VALUES (?,?,?,?,?,?,?,?,?,?)";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
//            ps.setString(1, id);
            ps.setString(1, nofac);
            ps.setString(2, fecha);
            ps.setString(3, hora);
            ps.setString(4, caj);
            ps.setString(5, nomcli);
            ps.setString(6, forpag);
            ps.setString(7, pro);
            ps.setString(8, sab);
            ps.setString(9, can);
            ps.setString(10, total);
            
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Factura Guardada");
                Limpiar();
                Mostrardatos("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TablaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void tfFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFacturaKeyPressed
        // TODO add your handling code here:
        
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String B = tfFactura.getText()+"";
        Mostrardatos(B);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_tfFacturaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFactura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbImprimirF;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel lblCajera;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigoC;
    private javax.swing.JLabel lblCodigoF;
    private javax.swing.JLabel lblDatosF;
    private javax.swing.JLabel lblDatosP;
    private javax.swing.JLabel lblFechaF;
    private javax.swing.JLabel lblFormapago;
    private javax.swing.JLabel lblHoraF;
    private javax.swing.JLabel lblNombreC;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblSaborH;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField tfCajera;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfCodigoC;
    private javax.swing.JTextField tfFactura;
    private javax.swing.JTextField tfFechaF;
    private javax.swing.JTextField tfFormaPago;
    private javax.swing.JTextField tfHora;
    private javax.swing.JTextField tfNombreC;
    private javax.swing.JTextField tfProducto;
    private javax.swing.JTextField tfSabor;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
