/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COPIAS;

import Connection.MyConnection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author A19B47948
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        jpLogin1 = new javax.swing.JPanel();
        lblContraseña = new javax.swing.JLabel();
        jbSesion = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jpContraseña = new javax.swing.JPasswordField();
        lblImagen1 = new javax.swing.JLabel();

        lblImagen.setText("jlevel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin1.setBackground(new java.awt.Color(255, 255, 255));

        lblContraseña.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblContraseña.setText("Contraseña");

        jbSesion.setText("INICIAR SESION");
        jbSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSesionActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblUsuario.setText("Usuario");

        lblInicio.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(0, 0, 102));
        lblInicio.setText("INICIO SESION");
        lblInicio.setToolTipText("");

        jtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLogin1Layout = new javax.swing.GroupLayout(jpLogin1);
        jpLogin1.setLayout(jpLogin1Layout);
        jpLogin1Layout.setHorizontalGroup(
            jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogin1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblContraseña))
                .addGap(25, 25, 25)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtUsuario)
                    .addComponent(jpContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogin1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogin1Layout.createSequentialGroup()
                        .addComponent(jbSesion)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogin1Layout.createSequentialGroup()
                        .addComponent(lblInicio)
                        .addGap(128, 128, 128))))
        );
        jpLogin1Layout.setVerticalGroup(
            jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogin1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblInicio)
                .addGap(53, 53, 53)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbSesion)
                .addGap(48, 48, 48))
        );

        getContentPane().add(jpLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 44, -1, -1));

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Helado.jpg"))); // NOI18N
        lblImagen1.setText("jlevel1");
        getContentPane().add(lblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSesionActionPerformed
        // TODO add your handling code here:

        try { 
        
        String Usuario, Password;
        
        Usuario = jtUsuario.getText();
        Password = jpContraseña.getText();
                            
        
        if ("Admin".equals(Usuario)&& "1234".equals(Password)){
            JOptionPane.showMessageDialog(rootPane, "Bienvenido " + Usuario);
            TablaUsuarios mf = new TablaUsuarios();
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
        }
        
        else{
            JOptionPane.showMessageDialog(rootPane, "Bienvenido" + Usuario);
            
            Factura mf = new Factura();
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
            this.dispose();
        }
        
        
        }
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
        
        
        this.dispose();
    }//GEN-LAST:event_jbSesionActionPerformed

    private void jtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSesion;
    private javax.swing.JPasswordField jpContraseña;
    private javax.swing.JPanel jpLogin1;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
