
package proyectofinalheladeria;

import Connection.MyConnection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Annibel y Clara
 */
public class frm2_InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public frm2_InicioSesion() {
        initComponents();
            setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        jpLogin1 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();
        lblInicio = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        jpContraseña = new javax.swing.JPasswordField();
        jbVolver = new javax.swing.JButton();
        lblImagen1 = new javax.swing.JLabel();

        lblImagen.setText("jlevel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin1.setBackground(new java.awt.Color(255, 255, 255));

        jbAceptar.setText("ACEPTAR");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        lblInicio.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblInicio.setText("INICIO SESION");
        lblInicio.setToolTipText("");

        lblUsuario.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblUsuario.setText("Usuario");

        jtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioActionPerformed(evt);
            }
        });

        lblContraseña.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblContraseña.setText("Contraseña");

        jbVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaVA.png"))); // NOI18N
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLogin1Layout = new javax.swing.GroupLayout(jpLogin1);
        jpLogin1.setLayout(jpLogin1Layout);
        jpLogin1Layout.setHorizontalGroup(
            jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogin1Layout.createSequentialGroup()
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLogin1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblInicio))
                    .addGroup(jpLogin1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogin1Layout.createSequentialGroup()
                                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseña)
                                    .addComponent(lblUsuario))
                                .addGap(37, 37, 37)
                                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtUsuario)
                                    .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogin1Layout.createSequentialGroup()
                                .addComponent(jbAceptar)
                                .addGap(79, 79, 79)))))
                .addGap(0, 81, Short.MAX_VALUE))
        );
        jpLogin1Layout.setVerticalGroup(
            jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogin1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogin1Layout.createSequentialGroup()
                        .addComponent(lblInicio)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(52, 52, 52)
                .addGroup(jpLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addGap(65, 65, 65)
                .addComponent(jbAceptar)
                .addGap(56, 56, 56))
        );

        getContentPane().add(jpLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 420, 390));

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EstampadoClara.jpg"))); // NOI18N
        lblImagen1.setText("jlevel1");
        getContentPane().add(lblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        // TODO add your handling code here:
        
        
        
        String Usuario, Password;
        
        Usuario = jtUsuario.getText();
        Password = new String (jpContraseña.getPassword());
        
      try {  
          
        PreparedStatement ps;
        ResultSet rs;
        Connection con = MyConnection.getConnection();
        String sql = "SELECT * FROM usuariof WHERE NombreUsuario=? AND Contraseña=?";
        ps = con.prepareStatement(sql);
        ps.setString(1, Usuario);
        ps.setString(2, Password);
        rs = ps.executeQuery();
        
        if (rs.next()){
            if (rs.getInt(6) == 1){
            JOptionPane.showMessageDialog(rootPane, "Bienvenido " + Usuario);
            String nombre__= rs.getString(2);
            
            frm_ControlUPP.nombre_ = nombre__;
            frm_ControlUPP mf = new frm_ControlUPP();
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
        }else{
                
            JOptionPane.showMessageDialog(rootPane, "Bienvenido " + Usuario);
            
            frm5_Facturacion mf = new frm5_Facturacion();
            String nombre_ = rs.getString(2);
            frm5_Facturacion.tfCajera.setText(nombre_);
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
            this.dispose();
        }
        
        }else{
           
              JOptionPane.showMessageDialog(rootPane, "Error, verifique que los datos existan");
        
        }
        } catch (SQLException ex) {
            Logger.getLogger(frm2_InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        
        
        this.dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        // TODO add your handling code here:
        frm1_Registro mf = new frm1_Registro();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm2_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm2_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm2_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm2_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm2_InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbVolver;
    public javax.swing.JPasswordField jpContraseña;
    private javax.swing.JPanel jpLogin1;
    public javax.swing.JTextField jtUsuario;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
