/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalheladeria;

import proyectofinalheladeria.frm4_Registrarse;
import Connection.MyConnection;
import Connection.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Annibel y Clara
 */
public class frm4_Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form LoginImagen
     */
    public frm4_Registrarse() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogin = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jbEnviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jpContraseña = new javax.swing.JPasswordField();
        jbReporte = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        cbRoles = new javax.swing.JComboBox<>();
        lblRol = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblNombre.setText("Nombre");

        j.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        j.setText("Contraseña");

        jbEnviar.setText("ENVIAR");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Correo");

        lblApellido1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblApellido1.setText("Usuario");

        jpContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpContraseñaActionPerformed(evt);
            }
        });

        jbReporte.setText("REPORTE");
        jbReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReporteActionPerformed(evt);
            }
        });

        lblLogin.setBackground(new java.awt.Color(255, 255, 102));
        lblLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblLogin.setText("REGISTRO");

        jbVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaVA.png"))); // NOI18N
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        cbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        lblRol.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblRol.setText("Rol");

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(lblLogin))
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpLoginLayout.createSequentialGroup()
                                    .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jpLoginLayout.createSequentialGroup()
                                            .addComponent(lblApellido1)
                                            .addGap(75, 75, 75))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpLoginLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jpLoginLayout.createSequentialGroup()
                                    .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(j)
                                        .addComponent(lblRol))
                                    .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpLoginLayout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(cbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(121, 121, 121))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpLoginLayout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addGap(71, 71, 71)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpLoginLayout.createSequentialGroup()
                                    .addComponent(jbEnviar)
                                    .addGap(87, 87, 87)
                                    .addComponent(jbReporte)
                                    .addGap(48, 48, 48))))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblLogin))
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellido1)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbReporte)
                            .addComponent(jbEnviar)))
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRol)
                            .addComponent(cbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(122, 122, 122))
        );

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 500, 380));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EstampadoClara.jpg"))); // NOI18N
        lblImagen.setText("jlevel1");
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        // Codigopara guaradar los datos de empleado cliente en la base de datos
        String nom = jtNombre.getText();
        String usu = jtUsuario.getText();
        String correo = jtCorreo.getText();
        String cont = jpContraseña.getText();
        String roles = cbRoles.getItemAt(cbRoles.getSelectedIndex());
        
//        int rroles = Integer.parseInt(roles);
        
        PreparedStatement ps;
        String query = "INSERT INTO `UsuarioF`(`Nombre`,`NombreUsuario`,`Correo`,`Contraseña`,`Id_rol`) VALUES (?,?,?,?,?)";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, nom);
            ps.setString(2, usu);
            ps.setString(3, correo);
            ps.setString(4, cont);
            ps.setString(5, roles);
            
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Nuevo dato ingresado");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frm4_Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        
        frm2_InicioSesion mf = new frm2_InicioSesion();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        
        this.dispose();
        
        
    }//GEN-LAST:event_jbEnviarActionPerformed

    private void jpContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpContraseñaActionPerformed

    private void jbReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReporteActionPerformed
        // TODO add your handling code here:
        
        Connection cn = MyConnection.getConnection();
        try{
          JasperReport jr = (JasperReport) JRLoader.loadObject(frm4_Registrarse.class.getResource("/Reporte/UsuarioF.jasper"));
          Map parametros = new HashMap<>();
          parametros.put("Titulo", "Reporte Usuarios");
            

          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true); 
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jbReporteActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        // TODO add your handling code here:
        frm1_Registro mf = new frm1_Registro();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm4_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm4_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm4_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm4_Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm4_Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbRoles;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jbReporte;
    private javax.swing.JButton jbVolver;
    private javax.swing.JPasswordField jpContraseña;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    // End of variables declaration//GEN-END:variables
}
