
package proyectofinalheladeria;

import Connection.MyConnection;
//import ProyectoHeladeria.LoginImagen1;
//import ProyectoHeladeria.PruebaTabla;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Annibel y Clara
 */
public class frm6_ControlProductos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    
    DefaultTableModel Producto;
    
    public frm6_ControlProductos() {
        initComponents();
        
        this.Producto = (DefaultTableModel) TablaProducto.getModel();
        this.setResizable(false);
        setLocationRelativeTo(null);
        Mostrardatos("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        jtDisponibilidad = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        jtProducto = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        lblDispobinilidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        jbReporte = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbInsertar = new javax.swing.JButton();
        jbVender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblProductos.setText("CONTROL PRODUCTOS");

        lblProducto.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblProducto.setText("Producto");

        jtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtProductoActionPerformed(evt);
            }
        });
        jtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtProductoKeyPressed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblPrecio.setText("Precio");

        lblCodigo.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblCodigo.setText("Codigo");

        jtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoActionPerformed(evt);
            }
        });

        lblDispobinilidad.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblDispobinilidad.setText("Disponibilidad");

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductoMouseClicked(evt);
            }
        });
        TablaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaProductoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProducto);

        jbReporte.setText("REPORTE");
        jbReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReporteActionPerformed(evt);
            }
        });

        jbLimpiar.setText("LIMPIAR");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbInsertar.setText("INSERTAR");
        jbInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertarActionPerformed(evt);
            }
        });

        jbVender.setText("VENDER");
        jbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVenderActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estanpado.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDispobinilidad)
                            .addComponent(lblCodigo)
                            .addComponent(lblPrecio)
                            .addComponent(lblProducto)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jbReporte)
                                .addGap(37, 37, 37)
                                .addComponent(jbLimpiar)
                                .addGap(51, 51, 51)
                                .addComponent(jbVender)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProductos)
                                .addGap(235, 235, 235))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblProductos)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDispobinilidad)
                        .addGap(18, 18, 18)
                        .addComponent(jtDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInsertar)
                    .addComponent(jbReporte)
                    .addComponent(jbLimpiar)
                    .addComponent(jbVender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoActionPerformed

    private void TablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductoMouseClicked
        // TODO add your handling code here:

        try {
            String Codigo = (String) Producto.getValueAt(TablaProducto.getSelectedRow(),0);
            String NProducto = (String) Producto.getValueAt(TablaProducto.getSelectedRow(),1);
            String Precio = (String) Producto.getValueAt(TablaProducto.getSelectedRow(),2);
            String Disponibilidad = (String) Producto.getValueAt(TablaProducto.getSelectedRow(),3);

            jtCodigo.setText(Codigo);
            jtProducto.setText(NProducto);
            jtPrecio.setText(Precio);
            jtDisponibilidad.setText(Disponibilidad);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaProductoMouseClicked

    private void jtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtProductoActionPerformed

    private void jtProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtProductoKeyPressed
        // TODO add your handling code here:

        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                String B = jtProducto.getText()+"";
                Mostrardatos(B);
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_jtProductoKeyPressed

    private void jbReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReporteActionPerformed
        // TODO add your handling code here:
        
        Connection cn=MyConnection.getConnection();
        
        try{
            JasperReport jr = (JasperReport) JRLoader.loadObject(frm6_ControlProductos.class.getResource("/Reporte/Producto.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Reporte Productos");
            

           JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
           JasperViewer jv = new JasperViewer(jp, false);
           jv.setVisible(true); 
        
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_jbReporteActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:

        Limpiar();
        Mostrardatos("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertarActionPerformed
        // TODO add your handling code here:
        String cod = jtCodigo.getText();
        String pro = jtProducto.getText();
        String pre = jtPrecio.getText();
        String can = jtDisponibilidad.getText();
        
        PreparedStatement ps;
        String query = "INSERT INTO `Producto`(`Codigo_producto`,`Producto`,`Precio`,`Disponibilidad`) VALUES (?,?,?,?)";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            //            ps.setString(1, id);
            ps.setString(1, cod);
            ps.setString(2, pro);
            ps.setString(3, pre);
            ps.setString(4, can);

            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Nuevo dato ingresado");
                Limpiar();
                Mostrardatos("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(frm6_ControlProductos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_jbInsertarActionPerformed

    private void jbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVenderActionPerformed
        // TODO add your handling code here:
        
        Enviar();
        
//        int Can1, Can2, ProductoV = 0;
//        
//        Can1 = Integer.parseInt(jtCantidad.getText());
//        Can2 = Integer.parseInt(jtCantidad.getText());
//        ProductoV = Can1-Can2;
//        
//        jtCantidad.setText(String.valueOf(ProductoV));
//        
//        String id = jtId.getText();
//        String nom = jtNombre.getText();
//        String pre = jtPrecio.getText();
//        String dis = jtDisponible.getText();
//        String can = jtCantidad.getText();
//        
//        PreparedStatement ps;
//        String query = "UPDATE `Producto` SET `CantidadDisponible`= ? WHERE `ID_producto`=";
//        try {
//            ps = MyConnection.getConnection().prepareStatement(query);
//
//            if(ps.executeUpdate() > 0)
//            {
//                JOptionPane.showMessageDialog(null, "Producto Vendido");
//                Limpiar();
//                Mostrardatos("");
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "error "+ex);
//        }
        
        
    }//GEN-LAST:event_jbVenderActionPerformed

    
    private void Enviar(){
       
        String Cod = jtCodigo.getText();
        String Dis = jtDisponibilidad.getText();
        
       PreparedStatement ps;
        String query = "UPDATE `Producto` SET `Disponibilidad`= Disponibilidad - "+Dis+" WHERE `Codigo_producto`=" + Cod;
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Producto Vendido");
                Limpiar();
                Mostrardatos("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(frm6_ControlProductos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    private void TablaProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaProductoKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String B = jtProducto.getText()+"";
        Mostrardatos(B);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaProductoKeyPressed

    
    
    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            Producto.addColumn("Codigo_producto");
            Producto.addColumn("Producto");
            Producto.addColumn("Precio");
            Producto.addColumn("Disponibilidad");

            this.TablaProducto.setModel(Producto);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM `Producto`";
            }
            else{
            sql="SELECT * FROM `Producto` WHERE `Codigo_producto`='"+valor+"'";
            } 

            String []datos=new String [6];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);

            Producto.addRow(datos);
            }
            TablaProducto.setModel(Producto);
            }catch(SQLException ex){
            Logger.getLogger(frm6_ControlProductos.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    
     public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        Producto.setColumnCount(0);
        Producto.setRowCount(0);
        TablaProducto.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    public void Limpiar(){
        //Funcion para limpiar los text field existentes
        try{
        jtCodigo.setText("");
        jtProducto.setText("");
        jtPrecio.setText("");
        jtDisponibilidad.setText("");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm6_ControlProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm6_ControlProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm6_ControlProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm6_ControlProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm6_ControlProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbInsertar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbReporte;
    private javax.swing.JButton jbVender;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDisponibilidad;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtProducto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDispobinilidad;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProductos;
    // End of variables declaration//GEN-END:variables
}
